- name: generate playbook and config file
  gather_facts: false
  hosts: localhost

  tasks: 
    - name: get current directory 
      ansible.builtin.shell: 
        cmd: pwd
      register: path
    - name: create playbook directory 
      ansible.builtin.file: 
        path: "{{ path.stdout }}/playbooks"
        state: directory 
    - name: load yaml config file
      include_vars: "{{ path.stdout }}/vars.yaml"
    - name: creating playbook.yaml in ./playbook/
      template: 
        src: jinja_templates/playbook.j2
        dest: "{{ path.stdout }}/playbooks/playbook.yaml"
