- hosts: localhost
  gather_facts: false
  tasks: 
    - name: get current directory
      ansible.builtin.shell: 
        cmd: pwd
      register: path

- hosts: localhost 
  name: generate playbook and config file
  gather_facts: false
  hosts: localhost
  tasks: 
    - name: create necessary directories
      ansible.builtin.file: 
        path: "{{ path.stdout }}/playbooks"
        state: directory
    - name: include vars
      include_vars: "{{ path.stdout }}/vars.yaml"
    - name: creating playbook.yaml in ./playbook/
      template: 
        src: jinja_templates/playbook.j2
        dest: ./playbooks/playbook.yaml
