- name: generate playbook and config file
  gather_facts: false
  hosts: localhost
  vars: 
    params: 
      files: 
        - vars.yaml 
  tasks: 
    - name: load yaml config file
      include_vars: vars.yaml
    - name: creating playbook.yaml in ./playbook/
      template: 
        src: /home/hashim/ansible-playbooks/config-replace/cat60_config.j2
        dest: /home/hashim/ansible-playbooks/config-replace/cat60_config
